Add error checking to finding the repo root

diff --git a/scripts/clean b/scripts/clean
--- a/scripts/clean
+++ b/scripts/clean
@@ -1,6 +1,12 @@
 #!/usr/bin/env sh
 
-REPO_ROOT=$(git rev-parse --show-toplevel)
+. "$(dirname "$0")/utils.sh"
+
+REPO_ROOT=$(get_repo_root); IS_REPO=$?
+if [ "$IS_REPO" -ne 0 ]; then
+    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
+    exit 1
+fi
 
 # clean up webpack artifacts
 if [ -d "$REPO_ROOT/build" ]; then
diff --git a/scripts/db b/scripts/db
--- a/scripts/db
+++ b/scripts/db
@@ -1,17 +1,14 @@
 #!/usr/bin/env sh
 
-cmd_is_valid() {
-    for valid_cmd in "export" "migrate" "reset";
-    do
-        if [ "$CMD" = "$valid_cmd" ]; then
-            return 0
-        fi
-    done
-    return 1
-}
+. "$(dirname "$0")/utils.sh"
 
-REPO_ROOT=$(git rev-parse --show-toplevel)
-CMD_DIR="$(realpath $(dirname "$0"))/db_ops"
+REPO_ROOT=$(get_repo_root); IS_REPO=$?
+if [ "$IS_REPO" -ne 0 ]; then
+    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
+    exit 1
+fi
+cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }
+
 CMD="$1"
 
 # validate input
@@ -20,7 +17,6 @@ if [[ -z "$1" ]] || ! cmd_is_valid; then
     exit 1
 fi
 
-cd "$REPO_ROOT"
 # try to run subcommand
 if [ -x "${CMD_DIR}/${CMD}.sh" ]; then
     shift
diff --git a/scripts/env b/scripts/env
--- a/scripts/env
+++ b/scripts/env
@@ -2,8 +2,13 @@
 
 . "$(dirname "$0")/utils.sh"
 
-REPO_ROOT=$(git rev-parse --show-toplevel)
-cd "$REPO_ROOT"
+REPO_ROOT=$(get_repo_root); IS_REPO=$?
+
+if [ "$IS_REPO" -ne 0 ]; then
+    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
+    exit 1
+fi
+cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }
 
 SUPPORTED_ENVS="prod dev"
 env_file=".env"
diff --git a/scripts/server b/scripts/server
--- a/scripts/server
+++ b/scripts/server
@@ -1,13 +1,13 @@
 #!/usr/bin/env sh
 
-cmd_is_valid() {
-    for valid_cmd in "up" "down";
-    do
-        if [ "$cmd" = "$valid_cmd" ]; then
-            return 0
-        fi
-    done
-    return 1
+. "$(dirname "$0")/utils.sh"
+
+REPO_ROOT=$(get_repo_root); IS_REPO=$?
+if [ "$IS_REPO" -ne 0 ]; then
+    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
+    exit 1
+fi
+cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }
 }
 
 REPO_ROOT=$(git rev-parse --show-toplevel)
