Only run webpack in a production setting

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -2,11 +2,22 @@
 
 # scripts/setup: Set up application for the first time after cloning, or set it
 #                back to the initial first unused state.
+. ./scripts/utils.sh
 
-"$(dirname "$0")/bootstrap"
+REPO_ROOT=$(get_repo_root); IS_REPO=$?
+if [ "$IS_REPO" -ne 0 ]; then
+    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
+    exit 1
+fi
+cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }
 
-# build webpack artifacts locally
+load_env || { echo "ERROR: Could not find .env file. Have you set up an environment with ./scripts/env?)" >&2; exit 1; }
+
+./scripts/bootstrap
+if [ "$PROJECT_ENV" = "prod" ]; then
+    # build webpack artifacts
+    echo '==> Running webpack build...'
 npm run build
 
-# create any missing database tables
-# psql -d $INFLOW_DB_URI -f $REPO_ROOT/database/schema/schema.sql
+    # build new docker image?
+fi
